apiVersion: gedgemig.gedge.etri.kr/v1
kind: Livmigration
metadata:
  name: checkpoint-79eb8dc8-6047-4591-8394-8b1c1a5900d1
  namespace: migration-test
  labels:
    name: checkpoint-79eb8dc8-6047-4591-8394-8b1c1a5900d1
spec:
  replicas: 0
  operation: checkpoint
  snapshotPath: /mnt/migrate/gedge-cls1
  sourcePod: podtest4
  selector:
    migPod:
