apiVersion: gedgemig.gedge.etri.kr/v1
kind: Livmigration
metadata:
  name: checkpoint-1d4ddf80-6a1b-4944-b895-116bfe2728a6
  namespace: default
  labels:
    name: checkpoint-1d4ddf80-6a1b-4944-b895-116bfe2728a6
spec:
  replicas: 0
  operation: checkpoint
  snapshotPath: /mnt/migrate/gedge-cls1
  sourcePod: aaa
  selector:
    migPod:
