apiVersion: gedgemig.gedge.etri.kr/v1
kind: Livmigration
metadata:
  name: checkpoint-38702f31-b26b-4c30-8df6-107e15d7fbd7
  namespace: migration-test
  labels:
    name: checkpoint-38702f31-b26b-4c30-8df6-107e15d7fbd7
spec:
  replicas: 0
  operation: checkpoint
  snapshotPath: /mnt/migrate/gedge-cls1
  sourcePod: nginxtest1
  selector:
    migPod:
