apiVersion: gedgemig.gedge.etri.kr/v1
kind: Livmigration
metadata:
  name: checkpoint-fda9db38-6dd7-4367-994c-50b72d0104f7
  namespace: default
  labels:
    name: checkpoint-fda9db38-6dd7-4367-994c-50b72d0104f7
spec:
  replicas: 0
  operation: checkpoint
  snapshotPath: /mnt/migrate/gedge-cls1
  sourcePod: nginx-test1-dns
  selector:
    migPod:
