apiVersion: gedgemig.gedge.etri.kr/v1
kind: Livmigration
metadata:
  name: checkpoint-3e5fcb5a-daac-46a7-98be-00e619523f30
  namespace: migration-test
  labels:
    name: checkpoint-3e5fcb5a-daac-46a7-98be-00e619523f30
spec:
  replicas: 0
  operation: checkpoint
  snapshotPath: /mnt/migrate/gedge-cls1
  sourcePod: nginx-test3
  selector:
    migPod:
